server:
  port: 8080

# SPRING ----------------------------------------------------------------------------------------------------
spring:
  application:
    name: building_management
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # DATASOURCE ----------------------------------------------------------------------------------------------------
  datasource:
    url: jdbc:mysql://reddit.ctmzootc3oh6.ap-south-1.rds.amazonaws.com:3306/btl_ltw
    username: admin
    password: 16102000
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA ----------------------------------------------------------------------------------------------------
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
  messages:
    basename: messages
    use-code-as-default-message: true

#
#cloud:
#  aws:
#    region:
#      auto: false
#      static: us-west-2
#    stack:
#      auto: false
#
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

application:
  swagger:
    base-url: localhost:8080
  jwt:
    confirmation-secret: 123456
    time-to-live: 3600 # seconds
